#!/usr/bin/python3

from datetime import datetime
import uuid
from models import storage

class BaseModel:
    def __init__(self, *args, **kwargs):


        my_uuid = str(uuid.uuid4())
        current_datetime = datetime.now()
        self.id = my_uuid
        self.created_at = current_datetime
        self.updated_at = current_datetime

        for key, value in kwargs.items():
            if key != "__class__":
                setattr(self, key, value)
                    

    def __str__(self):
        return f"[{self.__class__.__name__}] ({self.id}) {str(self.__dict__)}"

    def save(self):
        self.updated_at = datetime.now().isoformat()

    def to_dict(self):
        self.__dict__["__class__"] = self.__class__.__name__
        self.__dict__["created_at"] = self.created_at.isoformat()
        self.__dict__["updated_at"] = self.updated_at.isoformay()
        return self.__dict__

